ARG base="fedora"
FROM ${base}

# https://docs.yoctoproject.org/ref-manual/system-requirements.html#fedora-packages
# https://docs.yoctoproject.org/ref-manual/system-requirements.html#almalinux-packages
RUN \
    . /etc/os-release \
    ; if [[ "$ID" == "fedora" ]]; then \
        dnf install -y \
            perl-File-Compare \
            perl-File-Copy \
            perl-FindBin \
            perl-locale \
            python; \
      else \
        dnf install -y epel-release dnf-plugins-core; \
        dnf config-manager --set-enabled crb \
            || dnf config-manager --set-enabled powertools; \
        dnf makecache; \
      fi \
    ; dnf install -y \
        bzip2 \
        ccache \
        chrpath \
        cpio \
        cpp \
        diffstat \
        diffutils \
        file \
        findutils \
        gawk \
        gcc \
        gcc-c++ \
        git \
        glibc-devel \
        glibc-langpack-en \
        gzip \
        hostname \
        libacl \
        lz4 \
        make \
        patch \
        perl \
        perl-Data-Dumper \
        perl-Text-ParseWords \
        perl-Thread-Queue \
        perl-bignum \
        python3 \
        python3-GitPython \
        python3-jinja2 \
        python3-pexpect \
        python3-pip \
        rpcgen \
        socat \
        sudo \
        tar \
        texinfo \
        unzip \
        wget \
        which \
        xz \
        zstd \
    && for i in python3-websockets util-linux-script; do \
        if dnf info "$i" >/dev/null 2>&1; then \
            dnf install -y "$i"; \
        fi \
       done \
    && dnf clean all

ADD https://git.openembedded.org/openembedded-core/plain/scripts/oe-git-proxy /usr/local/bin/
RUN chmod 755 /usr/local/bin/oe-git-proxy

RUN \
    useradd -ms /bin/bash builder \
    && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER builder
RUN \
    echo '. <(buildenv init)' >> ~/.bashrc \
    && echo '[[ ${NO_PROXY} ]] || export NO_PROXY=$no_proxy' >> ~/.bashrc \
    && echo '[[ ${http_proxy} ]] && export GIT_PROXY_COMMAND=oe-git-proxy' >> ~/.bashrc \
    && git config --global user.email "builder@yocto" \
    && git config --global user.name "Yocto Builder" \
    && git config --global url."https://github.com/".insteadOf git://github.com/

USER root
WORKDIR /home/builder

COPY buildenv/entrypoint.sh /buildenv-entrypoint.sh
COPY buildenv/buildenv.sh /usr/local/bin/buildenv

COPY buildenv/buildenv.conf /etc/
COPY buildenv.d/ /etc/buildenv.d/

# The documents of extract and setup are chosen by this command.
COPY bin/yocto-flavor /usr/local/bin/

# The documents that extract and setup include are commands of buildenv
# as well, but they are not meant to be run by hand.
RUN \
    sed -i \
        -e 's/^#ALIASES=.*/ALIASES="extract setup build"/' \
        -e 's/^#DOTCMDS=.*/DOTCMDS=setup/' \
      /etc/buildenv.conf

ENTRYPOINT ["/buildenv-entrypoint.sh"]
CMD ["/bin/bash"]

ARG yocto_branch
ENV \
    LANG=en_US.UTF-8 \
    YOCTO_BITBAKE_TARGET=core-image-minimal \
    YOCTO_BRANCH=${yocto_branch} \
    YOCTO_BUILDTOOLS="" \
    YOCTO_BUILDTOOLS_OPTS="" \
    YOCTO_CCACHE_DIR="" \
    YOCTO_CONFIG="" \
    YOCTO_CONFIG_NAME="" \
    YOCTO_DISTRO="" \
    YOCTO_DL_DIR="" \
    YOCTO_MACHINE="" \
    YOCTO_SSTATE_DIR=""
