#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

build()
{
    distro=$1
    branch=${2:-}
    base=${distro}${branch:+-${branch}}

    if [ -e "Dockerfile.${distro}" ]; then
        docker build --build-arg yocto_branch=${branch} \
            ${DOCKER_BUILD_OPTS:-} \
            -t ${DOCKER_REPO}:${base} \
            -f Dockerfile.${distro} .
    else
        docker build --build-arg yocto_branch=${branch} \
            --build-arg ubuntu_version=${distro} \
            ${DOCKER_BUILD_OPTS:-} \
            -t ${DOCKER_REPO}:${base} \
            .
    fi
}

if [ $# -eq 0 ]; then
    for b in "" gatesgarth dunfell zeus warrior thud sumo rocko pyro morty krogoth jethro fido dizzy daisy; do
        build bionic "${b}"
        build xenial "${b}"
        build trusty "${b}"
    done

    docker tag ${DOCKER_REPO}:bionic ${DOCKER_REPO}

    for b in gatesgarth dunfell zeus warrior thud; do
        docker tag ${DOCKER_REPO}:bionic-${b} ${DOCKER_REPO}:${b}
    done

    for b in sumo rocko pyro morty krogoth; do
        docker tag ${DOCKER_REPO}:xenial-${b} ${DOCKER_REPO}:${b}
    done

    for b in jethro fido dizzy daisy; do
        docker tag ${DOCKER_REPO}:trusty-${b} ${DOCKER_REPO}:${b}
    done
else
    build "$@"
fi
