#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

build()
{
    distro=$1
    branch=${2:-}
    base=${distro}${branch:+-${branch}}

    if [ -e "Dockerfile.${distro}" ]; then
        docker build --build-arg yocto_branch=${branch} \
            ${DOCKER_BUILD_OPTS:-} \
            -t ${DOCKER_REPO}:${base} \
            -f Dockerfile.${distro} .
    else
        docker build --build-arg yocto_branch=${branch} \
            --build-arg ubuntu_version=${distro} \
            ${DOCKER_BUILD_OPTS:-} \
            -t ${DOCKER_REPO}:${base} \
            .
    fi
}

if [ $# -eq 0 ]; then
    for b in daisy dizzy fido jethro krogoth morty pyro rocko sumo thud \
            warrior zeus dunfell gatesgarth hardknott honister kirkstone ""; do
        build trusty "${b}"
        build xenial "${b}"
        build bionic "${b}"
        build focal "${b}"
    done

    docker tag ${DOCKER_REPO}:focal ${DOCKER_REPO}

    for b in gatesgarth hardknott honister kirkstone; do
        docker tag ${DOCKER_REPO}:bionic-${b} ${DOCKER_REPO}:${b}
    done

    for b in thud warrior zeus dunfell; do
        docker tag ${DOCKER_REPO}:bionic-${b} ${DOCKER_REPO}:${b}
    done

    for b in krogoth morty pyro rocko sumo; do
        docker tag ${DOCKER_REPO}:xenial-${b} ${DOCKER_REPO}:${b}
    done

    for b in daisy dizzy fido jethro; do
        docker tag ${DOCKER_REPO}:trusty-${b} ${DOCKER_REPO}:${b}
    done
else
    build "$@"
fi
