name: Publish Docker image
on: [push]
jobs:
  build_and_push_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [xenial, bionic, focal]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            anyakichi/yocto-builder
            ghcr.io/anyakichi/yocto-builder
          tags: ${{ matrix.version }}-master
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.ubuntu
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: ubuntu_version=${{ matrix.version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build_and_push:
    runs-on: ubuntu-latest
    needs: [build_and_push_ubuntu]
    env:
      DEFAULT_PAIRS:
        xenial-krogoth xenial-morty xenial-pyro xenial-rocko xenial-sumo
        bionic-thud bionic-warrior bionic-zeus bionic-dunfell
        focal-gatesgarth focal-hardknott focal-honister focal-kirkstone
    strategy:
      matrix:
        base: [xenial, bionic, focal]
        branch:
          [
            krogoth,
            morty,
            pyro,
            rocko,
            sumo,
            thud,
            warrior,
            zeus,
            dunfell,
            gatesgarth,
            hardknott,
            honister,
            kirkstone,
          ]
    steps:
      - run: |
          tag="${{ matrix.base }}-${{ matrix.branch }}"
          echo "TAGS<<EOF" >> $GITHUB_ENV
          echo "$tag" >> $GITHUB_ENV
          if [[ "$DEFAULT_PAIRS" == *"$tag"* ]]; then
            echo "${{ matrix.branch }}" >> $GITHUB_ENV
          fi
          echo EOF >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            anyakichi/yocto-builder
            ghcr.io/anyakichi/yocto-builder
          tags: ${{ env.TAGS }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: |
            base=${{ matrix.base }}-master
            yocto_branch=${{ matrix.branch }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
