name: Publish Docker image
on:
  push:
  schedule:
    - cron: "40 15 1 * *"
  workflow_dispatch:
jobs:
  build_and_push_base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: [ubuntu:xenial, ubuntu:bionic, ubuntu:focal, ubuntu:jammy, ubuntu:noble]
    steps:
      - id: tags
        run: |
          base="${{ matrix.base }}"
          echo "tags=${base##*:}-main" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            anyakichi/yocto-builder
            ghcr.io/anyakichi/yocto-builder
          tags: ${{ steps.tags.outputs.tags }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: ubuntu_version=${{ matrix.base }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build_and_push_fedora:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: [fedora, almalinux:8, almalinux:9]
    steps:
      - id: tags
        run: |
          base="${{ matrix.base }}"
          echo "tags=${base/:/}-main" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            anyakichi/yocto-builder
            ghcr.io/anyakichi/yocto-builder
          tags: ${{ steps.tags.outputs.tags }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.fedora
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: base=${{ matrix.base }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build_and_push:
    runs-on: ubuntu-latest
    needs: [build_and_push_base]
    env:
      DEFAULT_PAIRS:
        xenial-krogoth xenial-morty xenial-pyro xenial-rocko xenial-sumo
        bionic-thud bionic-warrior bionic-zeus bionic-dunfell
        focal-gatesgarth focal-hardknott focal-honister focal-kirkstone
        jammy-langdale jammy-nanbield jammy-scarthgap jammy-styhead
        noble-styhead noble-walnascar
    strategy:
      matrix:
        base: [xenial, bionic, focal, jammy, noble, fedora, almalinux8, almalinux9]
        branch:
          - krogoth
          - morty
          - pyro
          - rocko
          - sumo
          - thud
          - warrior
          - zeus
          - dunfell
          - gatesgarth
          - hardknott
          - honister
          - kirkstone
          - langdale
          - mickledore
          - nanbield
          - scarthgap
          - styhead
          - walnascar
    steps:
      - run: |
          tag="${{ matrix.base }}-${{ matrix.branch }}"
          echo "TAGS<<EOF" >> $GITHUB_ENV
          echo "$tag" >> $GITHUB_ENV
          if [[ "$DEFAULT_PAIRS" == *"$tag"* ]]; then
            echo "${{ matrix.branch }}" >> $GITHUB_ENV
          fi
          echo EOF >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            anyakichi/yocto-builder
            ghcr.io/anyakichi/yocto-builder
          tags: ${{ env.TAGS }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.env
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: |
            base=${{ matrix.base }}-main
            yocto_branch=${{ matrix.branch }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
